### ISSUE TITLE
Rules validation error during property creation with failAction behavior

### ISSUE THREAD

**Issue by siwyd** [akamai/terraform-provider-akamai#175]
### Terraform Version
Terraform v0.12.28
Akamai v0.8.0

### Affected Resource(s)
- akamai_property

### Terraform Configuration Files
Reproducible with a site failover behavior like this:
```
                    {
                        "name": "failAction",
                        "options": {
                            "enabled": true,
                            "actionType": "RECREATED_CO",
                            "contentHostname": "foobar.failover.company.invalid",
                            "contentCustomPath": false
                        }
                    }
```

### Expected Behavior
Property should be created.

### Actual Behavior
`foobar.failover.company.invalid` is defined in the edge hostnames, but during property creation I got a rules validation error stating that the hostname used for failover should be in the edge hostnames (sorry, haven't saved the exact error, was a few days ago). The property was created at that point, so I worked around it by untainting the resource and manually adding the edge hostnames, then running Terraform again and it went through.

Looking at the provider code, I see that the edge hostnames get set after the rules get validated during property creation. Maybe this should be the other way and the problem would not present itself then? The same might apply to an update action, I haven't looked into that.

**Comment by zstlaw** [comment]
Thanks for reporting this issue. It was fixed in the 1.0.0 release. Rules are now being set after hostnames in the property resource. Please upgrade to 1.0.0. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for additional details related to migration to 1.0.0 version of the provider.

If you encounter an issue with 1.0.0, testing your scenario, please submit a new issue.
