### ISSUE TITLE
contract ID no longer obtainable with latest provider

### ISSUE THREAD

**Issue by mohammadkandy** [akamai/terraform-provider-akamai#182]
### Terraform Version
* Terraform v0.12.20
* provider.akamai 0.9.1

### Affected Resource(s)
* data.akamai_contract.default
* data.akamai_group.group

### Terraform Configuration Files
```hcl
data "akamai_group" "group" {
  name = "Test-${upper(var.env)}"
}

data "akamai_contract" "default" {
}
```

### Debug Output
```
2020/09/09 20:09:32 [ERROR] <root>: eval: *terraform.EvalReadData, err: looking up group with name: "Test-D": contract ID is required for non-default name: Test-D
2020/09/09 20:09:32 [ERROR] <root>: eval: *terraform.EvalSequence, err: looking up group with name: "Test-D": contract ID is required for non-default name: Test-D
```

### Expected Behavior
Terraform plan successfully executes

### Actual Behavior
Not finding contract ID

### Steps to Reproduce
- terraform init
- terraform plan

### Important Factoids
The following issues is non-exists with provider v0.8.2 (last known working version).  Upgrading to latest version of provider outputs this behavior detailed above.

**Comment by zstlaw** [comment]
We were having issues with users with multiple contracts and groups since it is possible to have multiple groups with the same name.  We are migrating to making contract required field.  Can you try 

```
data "akamai_group" "group" {
  name = "Test-${upper(var.env)}"
  contract = data.akamai_contract.default.id
}

data "akamai_contract" "default" {
  group = "Test-${upper(var.env)}"
}
```

This will ensure that the contract is loaded for the specified group and the group is the one associated with the contract.
We are hoping to have better datasources for listing groups and contracts in the future but some of the current default logic had dangerous edge cases we are attempting to clean up.

**Comment by zstlaw** [comment]
We are currently working on updating the documentation.

**Comment by mohammadkandy** [comment]
@zstlaw Apologies for delayed response.

I can confirm after updating to above snippet the issue is resolved with latest provider version. Thank you kindly for this.
