### ISSUE TITLE
Datasource for SiteShield cidr map

### ISSUE THREAD

**Issue by spol-vt** [akamai/terraform-provider-akamai#235]
Hi there!

It would be great to have a `datasource` to fetch `SiteShield` cidr map.
Typical use case would be to read the map and use as value for AWS security group and similar terraform resources.

This is CLI example (using _firewall_ module) to fetching such map:
`akamai ss list-cidrs --map-id <ID>`

**Comment by netflash** [comment]
Any chance this can be pushed further?

**Comment by mgwoj** [comment]
Hello @netflash 

We are considering this enhancement for a future release, but do not yet have any timeline.

Thanks,
Michal

**Comment by nhemchand** [comment]
May i know what will be appetite to get this prioritized.
This will be a fantastic feature if you can get this rolling.

**Comment by lkowalsk-akamai-com** [comment]
@nhemchand , this is on the roadmap and will be added, but ther are other priorities for now that are closer to being implemented. Thank you for your patience for now.

**Comment by evanatuo** [comment]
@lkowalsk-akamai-com 

It's been almost a year since the last update here. Has the team come any closer to including this? 

Is there any workaround here? Maybe an example of using a Terraform http data resource to collect sitemap information?

I'd rather not have to dig information out of the UI for security groups by hand, but that seems like the only option right now.

**Comment by lkowalsk-akamai-com** [comment]
In order to keep things clean, I'm closing this ticket as a duplicate of this one: https://github.com/akamai/terraform-provider-akamai/issues/227. All status updates will be done in the mentioned ticket.
