### ISSUE TITLE
Cloud Access Manager - Support

### ISSUE THREAD

**Issue by carnei-ro** [akamai/terraform-provider-akamai#247]
Support managing CAM resources via Terraform would be awesome!

**Comment by carnei-ro** [comment]
@lkowalsk-akamai-com plans about this one?

**Comment by lkowalsk-akamai-com** [comment]
Hi @carnei-ro,
This is on our radmap for future relases, but cannot share any timelines just yet. Just to set the expectations, definietely not a Q1 2021.

**Comment by shohei-ihaya-dena** [comment]
Any updates?

**Comment by lkowalsk-akamai-com** [comment]
@carnei-ro, @shohei-ihaya-dena we are currently evaluating adding CAM support to Akamai Terraform Provider. Could you please let us know what kind of workflows/use cases you would like to see covered in this subprovider? We cannot promise they will be covered, but will be definitely considered.

**Comment by carnei-ro** [comment]
@lkowalsk-akamai-com IMHO at least:

- [ ] Create new Access Key (""""the keystore"""")
- [ ] Create new Access Key Version

Full CRUD would be perfect. Deleting an "Access Key" is not possible nowadays, not even by console or ticket.

**Comment by EdsonLuisVieira** [comment]
this functionality is very important for our workflow, this possibility would be very good

**Comment by fkieling** [comment]
Is where any new information when this feature will be supported?

**Comment by AndreasPrang** [comment]
@lkowalsk-akamai-com Could you please gibe us an update on this issue?

**Comment by lkowalsk-akamai-com** [comment]
Hi @fkieling, @AndreasPrang, thanks for showing interest in Akamai Terraform Provider and Cloud Access Manager. Currently this subprovider is in the backlog without any dates on when it will be implemented. I will share info when this changes.

**Comment by ASarco** [comment]
I arrived here looking for the same thing: the ability to create Access Keys and versions via Terraform.

What I need to do is to secure some AWS MediaPackageV2 endpoint to be accesible only by Akamai, following the instructions [here](https://docs.aws.amazon.com/mediapackage/latest/userguide/endpoint-auth.html) and [here](https://techdocs.akamai.com/cloud-access-mgr/docs/config-signing-property).  
The idea was to use Terraform to:

1. Create the IAM user
2. Create user access keys
3. Create Access Key in CAM using the recently created AWS access keys  _<-- this is what I'm missing_
4. Add created Access Key in property

Since there is no CAM subprovider, we can't automate the whole process, and some part will have to be done manually.

**Comment by lkowalsk-akamai-com** [comment]
I'm here to inform you that we are working on desing for Cloud Access Manager subprovider for Akamai Terraform Provider. I cannot share any dates, but the work is starting.

**Comment by fkieling** [comment]
Hi @lkowalsk-akamai-com,
can you say that's the timeline to release the support for Cloud Access Manager? Can you give an update?

**Comment by lkowalsk-akamai-com** [comment]
We are currently in the design phase and plan to have it available sometime in H1 of 2024, but this is tentative date.

**Comment by lkowalsk-akamai-com** [comment]
Hi @carnei-ro , @fkieling @AndreasPrang , @ASarco , @EdsonLuisVieira, @shohei-ihaya-dena 
I'm happy to inform you that Cloud Access functinality was added to the Akamai Terraform Provider in recent release.
