### ISSUE TITLE
Load Balancing Versions

### ISSUE THREAD

**Issue by insynwyn** [akamai/terraform-provider-akamai#295]
How do I add different Load Balancing Versions in Load Balancing Details with terraform?

### Terraform Version
Terraform v1.1.7
on windows_386

### Affected Resource(s)
- akamai_cloudlets_application_load_balancer

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

It depends what you want to do. Could you please give us more details?

In case that you want to create a new version of your ALB cloudlet: applying any update to your ALB cloudlet should generate a new version. [Documentation here](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/cloudlets_application_load_balancer)

In case that you want to import some existing ALB cloudlet with different versions to handle it with terraform, you may make use of the [import feature](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/cloudlets_application_load_balancer#import).

Please let us know

**Comment by insynwyn** [comment]
![Cloudlets Policy Manager - Luna 3-23-2022 9-33-52 AM](https://user-images.githubusercontent.com/1039657/159750245-311ed000-c66b-4d50-83b9-f667939b53ca.png)

**Comment by insynwyn** [comment]
How do I terraform for v1 and v2?

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

In the akamai terraform provider, we do not really care about v1 - just about the latest release. This is the way we intend the users to work after getting feedback from our clients.

Having said that, you may activate v1 in production and v2 in staging:

```
resource "akamai_cloudlets_application_load_balancer" "alb" {
  origin_id      = "org_1"
  network    = "PRODUCTION"
  description    = "test description"
}

resource "akamai_cloudlets_application_load_balancer_activation" "alb_prod" {
  origin_id = akamai_cloudlets_application_load_balancer.alb.origin_id
  network   = "production"
  version   = 1
  depends_on = [akamai_cloudlets_application_load_balancer.alb,  akamai_cloudlets_application_load_balancer_activation.alb_stag]
}

resource "akamai_cloudlets_application_load_balancer_activation" "alb_stag" {
  origin_id = akamai_cloudlets_application_load_balancer.alb.origin_id
  network   = "staging"
  version   = akamai_cloudlets_application_load_balancer.alb.version
  depends_on = [akamai_cloudlets_application_load_balancer.alb]
}
```

Please mind any possible syntax error in the script above, I am just typing from memory.

You may also add `version = akamai_cloudlets_application_load_balancer.alb.version` to `akamai_cloudlets_application_load_balancer_activation.alb_prod` if you always want to automatically roll the latest version to production network in case that `alb_stag` does not fail. Otherwise, if you prefer to do this manually, you may have to edit the script every time you want to push a new version to production (i.e. from version 1 to 2, 3, etc.).

Both activations should depend on the alb policy resource, and production activation should depend on staging activation (better to be safe than sorry).

Having that, you may extend the configuration with any extra details you may need.

I will close this task now, if you consider that the explanation is not good enough please do not hesitate to reopen and ask about the missing details ;-)

Kind regards,

Roberto

**Comment by insynwyn** [comment]
Trying to provision two different versions.  Everytime I update a
akamai_cloudlets_application_load_balancer
 it doesn't create a new version, it just modifies it.  Having trouble
creating the 2nd version.
I tried the below but it errored with " {origin_id} already exists".

resource "akamai_cloudlets_application_load_balancer"
"apt_alb_ecom_prd_useast1" {
  origin_id      = "APT_ALB_ECOM_PRD"
  description    = "100% East"
  balancing_type = "WEIGHTED"
  data_centers {
    cloud_server_host_header_override = false
    cloud_service = true
    country  = "US"
    continent = "NA"
    latitude = 38.96019
    longitude = -77.3545
    percent = 100
    hostname= "xxx.us-east-1.elb.amazonaws.com"
    state_or_province = "VA"
    city = "Reston"
    origin_id = "ECOMPRDUSEAST1"
  }
}

resource "akamai_cloudlets_application_load_balancer"
"apt_alb_ecom_prd_uswest2" {
  origin_id      = "APT_ALB_ECOM_PRD"
  description    = "100% West"
  balancing_type = "WEIGHTED"
  data_centers {
    cloud_server_host_header_override = false
    cloud_service = true
    country  = "US"
    continent = "NA"
    latitude = 45.91739
    longitude = -119.33174
    percent = 100
    hostname= "xxx.us-west-2.elb.amazonaws.com"
    state_or_province = "OR"
    city = "Umatilla"
    origin_id = "ECOMPRDUSWEST2"
  }
}

How do I provision two versions?

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

The way the ALB resource handles new versions is not so straight forward. As you can see in the [resource itself](https://github.com/akamai/terraform-provider-akamai/blob/master/pkg/providers/cloudlets/resource_akamai_cloudlets_application_load_balancer.go#L411):

If any of the following attributes have been modified: `description`, `balancing_type`, `data_centers`, `liveness_settings`:
1. If the given ALB version is active:  a new ALB version will be created.
2. If the given ALB version is not active: the ALB version is modified.

Is your version active? Could you please show us the output of the following commands?

- `terraform state show 'akamai_cloudlets_application_load_balancer.apt_alb_ecom_prd_useast1'`
- `terraform state show 'akamai_cloudlets_application_load_balancer.apt_alb_ecom_prd_uswest2'`

Please, mask any sensitive data :-)

If those versions which are stored in the local schema are not active in the server, it is normal that your ALB version is modified.

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

If you do not have any more questions, I will assume that my previous answers solved your doubts :-) Thus I will close this issue. Please, do not hesitate on reopening it if you still have problems.

Regards,

Roberto
