### ISSUE TITLE
Migrate an existing Akamai zone file into Terraform file

### ISSUE THREAD

**Issue by PrabhatRath** [akamai/terraform-provider-akamai#31]
Hi @dshafik ,

The customer asks the below -

**Will there be a possibility to migrate (called “import” in Terraform terms) an existing Akamai zone into a Terraform file, once the product is no longer in Beta state?** 

**How can we configure MX, SRV, and TXT records in the zone file?**

fyi @markkilmer

Thanks

**Comment by dshafik** [comment]
@PrabhatRath "import" in Terraform terms is for importing the existing _state_, not a configuration. This means that if you import, and then apply, it uses the imported state as the starting point for making changes, rather than no state, and applies whatever is in the configuration file. 

It does not modify or update the configuration file, and in fact you must add the resource configuration to be able to import at all.

Having said all that, while this is _not_ the solution they are looking for, (and beta state has no bearing on that) we do have plans for a config migration tool as part of Akamai CLI, however we do not have any kind of commitment date on it yet.

The answer to the second question is answered in the documentation which will go live with the provider. You can read the source markdown file rendered on GitHub [here](https://github.com/akamai/terraform-provider-akamai/blob/master/website/docs/r/fastdns_zone.html.markdown).

**Comment by PrabhatRath** [comment]
thank you. i will get back if the customer has more queries.
