### ISSUE TITLE
Moving Properties to Different Groups without State Management

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#329]
Properties may need to be moved to a different group.  Simply changing the group_id which is associated to the property, cp_code, and edge_hostname resulted in terraform errors about cp_code immutability and edge hostname updates.

In additon, moving the property via the gui and then updating the group ID in the TF (property, ehn, cpc) then ended up hitting bug https://github.com/akamai/terraform-provider-akamai/issues/322 with the cp_code (I believe).

As a result of the above, the process I found to move an unactivated newly-minted property with the TF:

1) Activate on staging
2) Move to final destination group
3) Drop the CP Code and EHN from the state file
4) Reimport the CP Code and EHN using the final destination group ID
5) Adjust group reference in our TF

What I'm hoping is the provider would be able to take a group change to the property, cp_code, and edge_hostname to move the property to a new group without having to do state management.

When the property is moved in the GUI, the cp_code is also added to the new group, assuming the property has been activated at least on staging.  So, the hope would be if we changed the group_id on the poperty, edge_hostname, and cp_code, that the property would move, which effectively places the cp_code in the destination group, and then the TF would be able to retrieve the cp_code (and similarly, edge_hostname) in the new group, as opposed to complaining about immutability.

Notes:

* I confirmed via API that the CP Code appears if the property was activated prior to move
* I moved the property to a lower group and haven't tested moving to similar-level groups
* While I have only tested with dropping both the EHN and CPC from state, when I attempted a move with existing state, both EHN and CPC complained; however, the EHN might have just been complaining due to CPC; as a result, I think dropping and reimporting the EHN along with the CPC is the cleanest if we have to use the "state rm" to perform this operation
* It was not necessary to drop the property from the state file which makes sense
* I have not tested if the EHN also gets placed in its destination group if the property is moved to a group where the EHN API is not reflecting it, as when I tested with groups in the same hierarchy, the EHN was already there

**Comment by mgwoj** [comment]
Hello @hypnotisttom ,

We will return to you once with evaluate it further.

Thanks,
Michal

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom 
Group changes for cpcode, property, and edgehostnames are not doable in PAPI nor PM.  Group management is done using the move tool with is a separate app scope and not something. Group membership is part of identity management and affects object permissions and scopes so it is hard to perform in an API where access is restricted by the group or contract associated with the current request.  (Papi and PM are both designed this way)  

Because group context changes and we consider group relationships immutable within the API I think the best action is similar to the cpcode workaround currently used.  (i.e. performing state removal and then reimport property with the new associations after the move is performed.)

**Comment by hypnotisttom** [comment]
Thank you for that description, and thank you for letting me submit the item.  Thanks for letting me know that the identified workaround is a viable option from your perspective.
