### ISSUE TITLE
can credential be passed via environment variables instead of .edgerc

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#407]
Can we pass credentials via environment variables instead of .edgerc?

**Comment by wzagrajcz** [comment]
Hello @BAu0002 
Thanks for opening the issue. Such approach would not align with the idea of declarative approach and is very error prone as the same `terraform apply` could have two different results from two different terminal windows.
Can You describe please what would You like to achieve with such approach and/or what problems does it solves?

Best regards,
Wojciech

**Comment by rolmo** [comment]
But with other providers this is also possible. Example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs

I don't understand why this should not fit to the declarative approach.

I am also looking for such a solution. If I run Terraform in a Github action, then I have to get the credentials to the runner somehow. But creating the "~/.edgerc" fails - ~or more precisely: Terraform ignores it on the GHA runner~. Therefore I am looking for alternatives.

In the meantime, the problem with the ignored edgerc file has been solved - this was due to a wrong format in this file (wrong line breaks) - but I still think it is the nicer approach to use environment variables instead of having to create a "~/.edgerc" temporarily.

**Comment by sebagomez** [comment]
hello @rolmo I think I'm facing a similar issue with my .edgerc file. I'm getting the following error even though the file there and it has everything expected

```bash
error reading Akamai EdgeGrid configuration: unable to load config from environment or .edgerc file: required option is missing from edgerc: "host"
```

I also suspected of the line breaks becase when I cat the file in the pipeline (I know 🙄) I see the file content in a single line... I've tried a lot of things but I'm working on Windows so don't know really how to fix it.

Any ideas?

**Comment by dawiddzhafarov** [comment]
Hi,

We encourage to use TF_VAR_<var_name> (https://developer.hashicorp.com/terraform/language/values/variables#environment-variables) together with config block:
1. First, export sample variable using `export TF_VAR_host=some_host_value`. 
2. Create variable block inside Your configuration:
```
variable "host" {
  type = string
  sensitive = true
  default = "default_value_if_var_not_exported"
}
```
3. You can use this variable in Your configuration, together with `config` block.
```
provider "akamai" {
  config {
    host = var.host
    client_secret = var.client_secret
    client_token = var.client_token
    access_token = var.access_token
  }
}
```

We will document `config` block, as currently it is not. Let me know if this way of using environment variables is sufficient for You.

@sebagomez could You please provide your edgerc configuration file (stripped of sensitive information)? How do You format it?

With regards,
Dawid

**Comment by sebagomez** [comment]
yes @dawiddzhafarov ! that did the trick, thanks!

here's my old edgerc file 
```txt
[default]
client_secret = Mw2Xz4zXXXXXXXXXXXXXXXX+qER0vrs=
host = akab-gXXXXXXXXXXXXXXXXXXXXX6unt.luna.akamaiapis.net
access_token = akab-XXXXXXXXXXXXXXXXXXXXjrhqu
client_token = akab-XXXXXXXXXXXXXXXXXXcfn7kl3
```

**Comment by KyleMarMcTVG** [comment]
The v4-proposed approach of using input variables to pass in the credentials is not equivalent to the removed v3 environment variable approach. It requires that users save their Akamai credentials in the Terraform state, and requires that four variables be passed around between Terraform configurations if custom modules are used. This is messy and makes the code a lot more brittle and insecure (if someone misses out a `sensitive = true` declaration on one variable, the credentials will be leaked).

Many Terraform providers operate successfully with authentication via environment variables - it's a clean, secure, standard way of operating. Our options now are to (1) store credentials in an unencrypted file (.edgerc) on the file system, which needs to be somehow shared between CI runners or (2) have the credentials passed about between providers and stored in the state file, which is also bad practice.

In addition, as pointed out in #444, the environment variable approach has not been properly deprecated and the note in the release notes that the feature working constitutes "undocumented support" is really hostile to your users - it's only undocumented because you removed it from the docs during v3 without deprecating it; it was a previously-supported and approved way of working.

I note that the link on the v5.0.0 release notes to propose this new approach to use the `config` block in the provider points to https://techdocs.akamai.com/terraform/docs/gs-authentication#use-inline-credentials, in which the `config` block authentication approach within the provider has been removed. Does this mean that this approach to `config` should be considered an undocumented feature, given that it has been deliberately removed from the documentation (even though the release notes suggest migrating to it)?

The v3 approach to environment variables was more secure, more straightforward and resulted in cleaner, more manageable code, and should be reinstated. Even if it isn't, the documentation around the alternative to an un-deprecated, breaking change should be updated as a priority so that the links in the release notes are accurate and point to up-to-date documentation.

**Comment by ericrichtert** [comment]
> The v4-proposed approach of using input variables to pass in the credentials is not equivalent to the removed v3 environment variable approach. It requires that users save their Akamai credentials in the Terraform state, and requires that four variables be passed around between Terraform configurations if custom modules are used. This is messy and makes the code a lot more brittle and insecure (if someone misses out a `sensitive = true` declaration on one variable, the credentials will be leaked).
> 
> Many Terraform providers operate successfully with authentication via environment variables - it's a clean, secure, standard way of operating. Our options now are to (1) store credentials in an unencrypted file (.edgerc) on the file system, which needs to be somehow shared between CI runners or (2) have the credentials passed about between providers and stored in the state file, which is also bad practice.
> 
> In addition, as pointed out in #444, the environment variable approach has not been properly deprecated and the note in the release notes that the feature working constitutes "undocumented support" is really hostile to your users - it's only undocumented because you removed it from the docs during v3 without deprecating it; it was a previously-supported and approved way of working.
> 
> I note that the link on the v5.0.0 release notes to propose this new approach to use the `config` block in the provider points to https://techdocs.akamai.com/terraform/docs/gs-authentication#use-inline-credentials, in which the `config` block authentication approach within the provider has been removed. Does this mean that this approach to `config` should be considered an undocumented feature, given that it has been deliberately removed from the documentation (even though the release notes suggest migrating to it)?
> 
> The v3 approach to environment variables was more secure, more straightforward and resulted in cleaner, more manageable code, and should be reinstated. Even if it isn't, the documentation around the alternative to an un-deprecated, breaking change should be updated as a priority so that the links in the release notes are accurate and point to up-to-date documentation.

I agree, from the terraform site [1]:

`Some providers can use shell environment variables (or other alternate sources, like VM instance profiles) as values for some of their arguments; when available, we recommend using this as a way to keep credentials out of your version-controlled Terraform code.
`
So please revert the change and enable the 4 ENV properties.

[1]: https://developer.hashicorp.com/terraform/language/providers/configuration

**Comment by dstopka** [comment]
Tracking updates with https://github.com/akamai/terraform-provider-akamai/issues/444#issuecomment-1625597862.

**Comment by mgwoj** [comment]
This issue was fixed in recent release.
