### ISSUE TITLE
tech_contact in akamai_cps_dv_enrollment

### ISSUE THREAD

**Issue by rolmo** [akamai/terraform-provider-akamai#412]
### Terraform Version
Terraform v1.4.6
provider registry.terraform.io/akamai/akamai v3.6.0

### Affected Resource(s)

akamai_cps_dv_enrollment

### Terraform Configuration Files
```hcl
resource "akamai_cps_dv_enrollment" "cert" {
    [...]
    tech_contact {
        first_name       = "<name of my account manager>"
        last_name        = "<name of my account manager>"
        phone               = "+4853xxxxxx"
        email                 = "xxxx@akamai.com"
        address_line_one = ""
        city             = ""
        country_code     = ""
        organization     = "Akamai"
        postal_code      = ""
        region           = ""
        title            = "Administrator"
    }
    [...]
}
```

### Problems

I don't think it's the right approach that I should enter my Akamai maintainer here and store it in our Git repository.

It would be better if I could just leave these fields empty and they will be populated on the Akamai side. Alternatively, there could be a data source that returns me the entire `tech_contact`.

Furthermore, the error checking and error message here is not satisfactory:

For example, if I leave the "phone" field blank or insert letters there, then a `terraform plan` runs through successfully, but with the `terraform apply` there is an error that doesn't tell you where the problem is:

```
│ Error: update enrollment: API error:
│ {
│ 	"type": "https://akab-yh7mrwvbenbjmqxe-x2eimenqravxg3xm.luna.akamaiapis.net/cps/v2/error-types/internal-error",
│ 	"title": "Internal Error",
│ 	"detail": "",
│ 	"instance": "https://akab-yh7mrwvbenbjmqxe-x2eimenqravxg3xm.luna.akamaiapis.net/cps/v2/error-types/internal-error?id=c8f599aa50b44358b18dc41cb65fa165",
│ 	"statusCode": 500
│ }
```

**Comment by wzagrajcz** [comment]
Hello @rolmo 
Thanks for opening the issue. I'm afraid that there is nothing that we can do about Your problem:
- the tech_contact is required to be present in the resource because that is how the CPS API works. When calling the API directly without technical contact provided it fails the request
- proposed data source cannot be created as we simply don't have such data on our side as Akamai maintainer for given account/contract
If You don't want to store Your Akamai maintainer in git, then You can move the values into terraform variables and keep the values in `.tfvars` file which will be not tracked (using gitignore) by git.

The error message is not clear and I can let CPS API team know to change it, but I have some issues in recreating the issue. Using the `akamai_cps_dv_enrollment` resource and modifying a working configuration by altering only technical_contact's phone with either `phone  = ""` or `phone = "abcdef"` I got a 400 error:
```
╷
│ Error: create enrollment: API error: 
│ {
│       "type": "https://.../cps/v2/error-types/validation-failure",
│       "title": "Failed Validation",
│       "detail": "Validation Failures: [ValidationFailure(fieldName=technical-contact.phone, message=Bad phone number abcdef)]",
│       "instance": "https://.....cps/v2/error-types/validation-failure?id=...",
│       "statusCode": 400
│ }
│ 
│   with akamai_cps_dv_enrollment.enrollment,
│   on main.tf line 15, in resource "akamai_cps_dv_enrollment" "enrollment":
│   15: resource "akamai_cps_dv_enrollment" "enrollment" {
│ 
╵

```
Do You keep getting this 500 error? If so, was Your configuration (except from the phone) correct (so running terraform apply finished successfully)? If no, what else was changed in it?

Best regards,
Wojciech

**Comment by rolmo** [comment]
@wzagrajcz,

yes, i have a full working "akamai_cps_dv_enrollment", in the "tech_contact", there is a attribute "phone" with value "+4853...." (the dotes only to hide the number here - that are real numbers). A "terraform plan" and "terraform apply" runs successful.

Then I change the phone number from "+4853...." to "x4853...." (replace the allowed plus sign by a "x").

- A `terraform plan` runs successful and shows as expected, that the "tech_contact" must replaced.
- But a `terraform apply` fails with:

```
akamai_cps_dv_enrollment.cert: Modifying... [id=179441]
│ Error: update enrollment: API error:
│ {
│ 	"type": "https://akab-yh7mrwvbenbjmqxe-x2eimenqravxg3xm.luna.akamaiapis.net/cps/v2/error-types/internal-error",
│ 	"title": "Internal Error",
│ 	"detail": "",
│ 	"instance": "https://akab-yh7mrwvbenbjmqxe-x2eimenqravxg3xm.luna.akamaiapis.net/cps/v2/error-types/internal-error?id=3f376bf2c677444aa09ef1f3b929f027",
│ 	"statusCode": 500
│ }
│
│   with akamai_cps_dv_enrollment.cert,
│   on certificate.tf line 4, in resource "akamai_cps_dv_enrollment" "cert":
│    4: resource "akamai_cps_dv_enrollment" "cert" {
```

**Comment by wzagrajcz** [comment]
Hello @rolmo 
Thank You for details regarding the recreation of the issue. Unfortunately even without those I was not able to reproduce the issue but I've contacted the CPS API team to take a look at it (as the issue seems not related to Terraform Provider Akamai).

I will update You when I know something more.

Best regards,
Wojciech

**Comment by lkowalsk-akamai-com** [comment]
Closing it due to lack of response. Please free to create a new ticket if needed.
