### ISSUE TITLE
DXE-1748 Akamai_Group Data Source cannot distinguish between groups with the same name

### ISSUE THREAD

**Issue by ajoslin103** [akamai/terraform-provider-akamai#414]
Akamai_Group only selects by  group_name

But there can be multiple groups with the same name

This problem is referenced with a TODO in the Akamai Provider source code

ref: https://github.com/carnei-ro/terraform-provider-akamai/blob/master/pkg/providers/property/data_property_akamai_group.go#L121

**Comment by wzagrajcz** [comment]
Hello @ajoslin103 
Thank You for opening the issue. We will work on reproducing it. 

Best regards,
Wojciech

**Comment by lkowalsk-akamai-com** [comment]
Hi @ajoslin103, it is currently not possible to create two groups with the same name. It was possible some time ago. Since the fix would require doing complex change, introducing breaking changes and need of use of ID we are not going to implement the fix. Our suggestion is to rename one of the groups to have unique names.

**Comment by ajoslin103** [comment]
I switched to specification by groupId - more accurate and always works.  Thanks.
