### ISSUE TITLE
DXE-2818 Evaluation of unused snippets is counter-intuitive

### ISSUE THREAD

**Issue by oliversalzburg** [akamai/terraform-provider-akamai#436]
### Terraform Version
1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_rules_template

### Expected Behavior
Only variables used in property snippets that are included in the tree are expected to be defined.

### Actual Behavior
Since 4.0, even unused snippets are validated, and processing will fail if variables are undefined. This is a breaking change, even though it wasn't listed as one.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Put a JSON file with `${env.doesntexist}` into your property snippets folder.

**Comment by wzagrajcz** [comment]
Hello @oliversalzburg 

Thank You for opening the issue.
The additional validation for variables in all snippets was mentioned in the `features/enhancements` section in 4.0.0 changelog. We had long internal discussions if we should consider that change as `enhancement` or `breaking change` but in the end decided to go with `enhancement` as we could not find any reason why user would like to have unused snippets inside his snippets directory (and definitely would like to know that they are not valid). Do You have business case where You need to have unused snippets in Your snippets directory without validation?

Thanks and best regards,
Wojciech

**Comment by oliversalzburg** [comment]
We have a single module to set up ION properties. This module includes lots of snippets, which we include in different `akamai_property_rules_template` instances. As those instances all point into the same snippet folder, this change breaks every single property. I assume this change will force us to migrate this module into multiple distinct modules, which seems like a redundant task.

Maybe I'm missing a cleaner solution altogether?

**Comment by wzagrajcz** [comment]
Thanks for quick response. That's the scenario that we didn't foresee. In such case this snippets failing during early evaluation does not make much sense. We will work on loosening it.

Thanks and best regards,
Wojciech

**Comment by vegardengen** [comment]
I will have the same issue when I upgrade.

We have a fairly large repository of snippets in a directory-structure with directories for several development teams. 

During our deploy pipeline, this directory is copied into the property-snippets directory for the deploying resource.

I am able to work around that for this purpose by copying in only those files II need, but I also have another workaround limitation for another enhancement that came around 2.3.0/2.4.0: That all JSON files had to be valid in itself, not only the result.

Since we include files in variables.json, and each of them might contain several variables a team has a need for, those included files is not valid json in itself. So what I did, was make an extra 

```
data "akamai_property_rules_template" "variables" {
  template_file = "./property-snippets/variables.json"
}

```
And then in the rules template, I'd reference it like this:

```
variables {
   name = "akamai_variables"
   value= jsonencode(flatten(jsondecode(data.akamai_property_rules_template.variables.json)))
   type = "jsonBlock"
 }
```

Instead of including variables.json in rules.json, I'll now just reference akamai_variables.

However, 4.0.0 breaks the variables akamai_property_rules_template, because it will find all the other files there, and not have variables for them.

So I will also need a solution for this one.

**Comment by oliversalzburg** [comment]
I have since rewritten all rule sets for all our sites with `akamai_property_rules_builder`. At least for our cases, this workflow is dramatically better than `akamai_property_rules_template`. We are so much more flexible in how we can construct our rule sets. This resource is a godsend. I should not have been scared of the "beta" label before. This is the way forward.

**Comment by vegardengen** [comment]
It looks good, yes.

I will have to try it, at some point. But right now, I have quite a bit of json-structures and quite a few teams that have gotten used to that way of writing stuff...


- Vegard

On Tue, Jul 25, 2023 at 11:31:54AM -0700, Oliver Salzburg wrote:
> I have since rewritten all rule sets for all our sites with `akamai_property_rules_builder`. At least for our cases, this workflow is dramatically better than `akamai_property_rules_template`. We are so much more flexible in how we can construct our rule sets. This resource is a godsend. I should not have been scared of the "beta" label before. This is the way forward.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/akamai/terraform-provider-akamai/issues/436#issuecomment-1650336816
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

-- 
- Vegard Engen, member of the first RFC1149 implementation team.

**Comment by lkowalsk-akamai-com** [comment]
This issue is now fixed in recent release.
