### ISSUE TITLE
EdgeDNS TXT record trimmed

### ISSUE THREAD

**Issue by izzm** [akamai/terraform-provider-akamai#537]
Hi there,

After upgrading to version 5.5+, I discovered a change in the behavior of creating TXT records containing semicolons and spaces.

### Terraform Version
```
Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v6.0.0
```

### Affected Resource(s)
- akamai_dns_record

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "this" {
  name        = "test.example.com"
  recordtype  = "TXT"
  target      = [
      "a=test b=1",
      "a=test; b=2",
      ";a=test b=3",
  ]
  ttl         = 3600
  zone    = "example.com"
}
```

### Expected Behavior
TXT records are created as they present in configuration

### Actual Behavior
TXT records are trimmed after semicolon and spaces are escaped with double quotes.

<img width="919" alt="Screenshot 2024-03-26 at 22 01 27" src="https://github.com/akamai/terraform-provider-akamai/assets/1209784/8de7843c-56f5-4e49-92e4-e877bb59d8e6">

Second `terraform apply` run produces plan with:

```hcl
~ target     = [
  - "\"\"",
  + "a=test b=1",
    "a=test; b=2",
  - "\"a=test\" \"b=1\"",
  + ";a=test b=3",
]
```

### Steps to Reproduce
1. `terraform apply`
2. verify record at https://control.akamai.com

### Related issues
https://github.com/akamai/terraform-provider-akamai/issues/430

**Comment by mimazaka** [comment]
Hi @izzm ,

Thank you for rising this ticket. I was able to reproduce trimming behavior, but it seemed to work as designed. In order to avoid trimming after space or semicolon, you have to provide additional `\"` at the begging and end of target eg. `"\"a=test b=1\""`. 

For full explanation of trimming txt record after escaping characters please refer to [RFC 1035 ](https://datatracker.ietf.org/doc/html/rfc1035) for quoting details (Page 34,35).

Best regards,

**Comment by izzm** [comment]
Hi @mimazaka ,

Thank you, additional `\"` fixed the problem.
