### ISSUE TITLE
feature request - secure provisioning service

### ISSUE THREAD

**Issue by an774a** [akamai/terraform-provider-akamai#64]
Hello -- please add SPS support ( https://developer.akamai.com/api/core_features/secure_provisioning_service/v1.html ) to this provider.

Thank you!

**Comment by ghost** [comment]
Thanks for the feedback!

Certificate management and the ability to create Secure EdgeHostname on Akamai is a high priority feature to have enabled in the Akamai provider. This is on the roadmap.

Today you are able to create Edge Hostnames and map them to a slot number with the current resources.

**Comment by sidph** [comment]
Hi @an774a  - we are in the process of retiring the SPS API since we have the workflow [here](https://learn.akamai.com/en-us/learn_akamai/getting_started_with_akamai_developers/core_features/create_edgehostnames.html) enabled. You should be able to provision a secure edgehostname without needing SPS via the terraofrm provider (hint: use the edgekey.net hostname)
